ORG 0
WORD 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39 ; 0-9
WORD 2D ; -
WORD 2B ; +
WORD 2F ; /
WORD 2A ; *
WORD 2E ; .
WORD 3D ; =
WORD 0x8000
OUTPUT_STACK: WORD 31 DUP (0x8000), 0x8000
OUTPUT_STACK_START: WORD $OUTPUT_STACK
WORD 0x8000
OPERAND_STACK: WORD 31 DUP (?), 0x8000
OPERAND_STACK_POINTER: WORD $OPERAND_STACK
STOPPER: WORD 0x8000
MINUS: WORD 0x800A
PLUS: WORD 0x800B
DIV_SIGN: WORD 0x800C
MULT_SIGN: WORD 0x800D
EQUAL: WORD 0x800F
OPERAND1: WORD ?
OPERAND1_PRIORITY: WORD ?
OPERAND2: WORD ?
OPERAND2_PRIORITY: WORD ?
OR_MASK_OPERAND_PRIORITY: WORD 0x4000
OR_MASK_OPERAND_GENERAL: WORD 0x2000
GET_FIRST_4_BITS: WORD 0xF000
OPERAND_CHECKER: WORD 0xF000
CHECK_FOR_EQUAL_SIGN: WORD 0xE00F
SUM_TWO_HUNDRED: WORD 0x0200

CLA
OUT 0xC
AWAIT_INPUT:
	IN 0x1D
	AND #0x40
	BEQ AWAIT_INPUT
IN 0x1C
ST $CHAR
CMP #0xA
BPL ISNT_NUMBER
IS_NUMBER:
	LD $NUM
	ASL
	ASL
	ASL
	ADD $NUM
	ADD $NUM
	ADD $CHAR
	ST $NUM
	JUMP $PRINT
ISNT_NUMBER:
	CMP #0xC
	BPL SK
		OR $OR_MASK_OPERAND_PRIORITY
	SK: CMP #0xF
	BNE SK1
		OR $OR_MASK_OPERAND_PRIORITY
	SK1: OR $STOPPER
	OR $OR_MASK_OPERAND_GENERAL
	ST $CHAR

	LD $NUM
	ST (OUTPUT_STACK_POINTER)+
	CLA
	ST $NUM

	FLUSHING:
		LD -(OPERAND_STACK_POINTER)
		CMP $STOPPER
		BEQ END_FLUSH
		ST $OPERAND1
		AND $OR_MASK_OPERAND_PRIORITY
		ST $OPERAND1_PRIORITY
		LD $CHAR
		AND $OR_MASK_OPERAND_PRIORITY
		CMP $OPERAND1_PRIORITY
		BGE FLUSH_OPERAND
		JUMP $END_FLUSH
		FLUSH_OPERAND:
			LD $OPERAND1
			ST (OUTPUT_STACK_POINTER)+
			JUMP $FLUSHING
	END_FLUSH:
	CMP (OPERAND_STACK_POINTER)+
	
	LD $CHAR
	CMP $CHECK_FOR_EQUAL_SIGN
	BEQ PREPARE_FOR_FINISH
	ST (OPERAND_STACK_POINTER)+
PRINT:
	LD (CHAR)
	OUT 0xC
	JUMP $AWAIT_INPUT

PREPARE_FOR_FINISH:
	CLA
	ST $OUTPUT_STACK_FIXER_POINTER
	LD $OUTPUT_STACK_START
	ST $OUTPUT_STACK_POINTER
FINISH:
	LD (OUTPUT_STACK_POINTER)+
	AND $GET_FIRST_4_BITS
	CMP $OPERAND_CHECKER
	BPL FINISH

	CMP $STOPPER
	BNE NOT_END
	LD -(OUTPUT_STACK_POINTER)
	LD -(OUTPUT_STACK_POINTER)
	ST $FINAL_NUMBER
	JUMP $ENDER

	NOT_END:
	LD -(OUTPUT_STACK_POINTER)
	ADD $SUM_TWO_HUNDRED
	ST $OP_TO_DO
	LD -(OUTPUT_STACK_POINTER)
	ST $SECOND_VAR
	LD $OUTPUT_STACK_POINTER
	ST $OUTPUT_STACK_FIXER_POINTER
	LD -(OUTPUT_STACK_POINTER)
	PUSH
	LD $SECOND_VAR
	PUSH
	CALL (OP_TO_DO)
	POP
	POP
	ST (OUTPUT_STACK_POINTER)+
	LD $STOPPER
	ST (OUTPUT_STACK_POINTER)+
	ST (OUTPUT_STACK_POINTER)+

	MOVE_ELEMENTS:
		LD (OUTPUT_STACK_POINTER)
		CMP $STOPPER
		BEQ STOP_FIX
		ST (OUTPUT_STACK_FIXER_POINTER)+
		LD $STOPPER
		ST (OUTPUT_STACK_POINTER)+
		JUMP $MOVE_ELEMENTS
	STOP_FIX:
		CLA
		ST $OUTPUT_STACK_FIXER_POINTER
		LD $OUTPUT_STACK_START
		ST $OUTPUT_STACK_POINTER
		JUMP $FINISH
ENDER:
	LD (CHAR)
	OUT 0xC
CONVERT_ANSWER_TO_DECIMAL:
	LD $FINAL_NUMBER
	BPL IS_POSITIVE
	LD #1
	ST $FINISH_MINUS_STATE
	LD $FINAL_NUMBER
	NEG
	IS_POSITIVE:
	CONVERSION:
		PUSH
		LD #10
		PUSH
		CALL $DIVISION
		POP
		ST (LEFTOVERS_POINTER)+
		POP
		CMP #10
		BPL CONVERSION
	CMP #0
	BEQ REFUSE_ZERO
	ST (LEFTOVERS_POINTER)+
	REFUSE_ZERO: LD $FINISH_MINUS_STATE
	BEQ LEFTOVERS_PRINT
	LD #0x2D
	OUT 0xC
	LD #0
	ST $FINISH_MINUS_STATE
	LEFTOVERS_PRINT:
		LD -(LEFTOVERS_POINTER)
		CMP $STOPPER
		BEQ KONEC
		CMP #0xA
		BPL KONEC
		ST $LEFTOVER_TO_PRINT
		LD (LEFTOVER_TO_PRINT)
		OUT 0xC
		LD $STOPPER
		ST (LEFTOVERS_POINTER)
		JUMP $LEFTOVERS_PRINT
KONEC:
CMP (LEFTOVERS_POINTER)+
HLT
HLT
CHAR: WORD ?
HLT
NUM: WORD ?
HLT
OP_TO_DO: WORD ?
SECOND_VAR: WORD ?
FIRST_VAR: WORD ?
FINAL_NUMBER: WORD ?
OUTPUT_STACK_POINTER: WORD $OUTPUT_STACK
OUTPUT_STACK_FIXER_POINTER: WORD ?
WORD 0x8000
WORD 0x8000
LEFTOVERS: WORD 10 DUP (0x8000)
LEFTOVERS_POINTER: WORD $LEFTOVERS
LEFTOVER_TO_PRINT: WORD ?
FINISH_MINUS_STATE: WORD ?





ADDITION:
	LD &2
	ADD &1
	ST &2
	RET

SUBTRACTION:
	LD &2
	SUB &1
	ST &2
	RET

MINUS_STATE: WORD ?
RESULT: WORD ?
MULTIPLICATION:
	CLA
	ST $MINUS_STATE
	LD &1
	BPL SECOND_NOT_MINUS
	SECOND_MINUS:
		NEG
		ST &1
		LD $MINUS_STATE
		ADD $STOPPER
		ST $MINUS_STATE
	SECOND_NOT_MINUS: LD &2
	BPL FIRST_NOT_MINUS
	FIRST_MINUS:
		LD $MINUS_STATE
		ADD $STOPPER
		ST $MINUS_STATE
		LD &2
		NEG
		ST &2
	FIRST_NOT_MINUS: BEQ STOP_LOOP
	JUMP $START_LOOP
	ADD_LOOP:
		ADD &2
		START_LOOP: LOOP &1
		JUMP $ADD_LOOP
	STOP_LOOP:
		ST $RESULT
		LD $MINUS_STATE
		BPL EXIT_MULTIPLICATION
			LD $RESULT
			NEG
			ST &2
			RET
		EXIT_MULTIPLICATION: LD $RESULT
		ST &2
		RET

DIVISIBLE: WORD ?
DIVIDE_BY: WORD ?
DIV_RESULT: WORD ?
DIV_MINUS_STATE: WORD ?
DIVISION:
	CLA
	ST $DIV_RESULT
	ST $DIV_MINUS_STATE
	LD &2
	BPL DIVISIBLE_NOT_MINUS
		LD $DIV_MINUS_STATE
		ADD $STOPPER
		ST $DIV_MINUS_STATE
		LD &2
		NEG
		ST &2
	DIVISIBLE_NOT_MINUS:
	LD &2
	ST $DIVISIBLE
	LD &1
		BPL DIVIDE_BY_NOT_MINUS
		LD $DIV_MINUS_STATE
		ADD $STOPPER
		ST $DIV_MINUS_STATE
		LD &1
		NEG
		ST &1
	DIVIDE_BY_NOT_MINUS:
	LD &1
	ST $DIVIDE_BY
	DIVIDE:
		LD $DIVISIBLE
		CMP $DIVIDE_BY
		BMI STOP
		SUB $DIVIDE_BY
		ST $DIVISIBLE
		LD $DIV_RESULT
		INC
		ST $DIV_RESULT
		JUMP $DIVIDE
	STOP:
	LD $DIV_MINUS_STATE
	BPL DIV_STATE_PLUS
		LD $DIV_RESULT
		NEG
		ST $DIV_RESULT
	DIV_STATE_PLUS: LD $DIV_RESULT
	ST &2
	LD $DIVISIBLE
	ST &1
RET







ORG 0x20A
JUMP $SUBTRACTION
JUMP $ADDITION
JUMP $DIVISION
JUMP $MULTIPLICATION