;0x8000 - Конец стэка / Удалённый элемент
STACK: WORD 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0x8000
STACK_START: WORD $STACK
STACK_POINTER: WORD $STACK
STACK_FIX_POINTER: WORD ?
STOPPER: WORD 0x8000

LD (STACK_POINTER)+
LD (STACK_POINTER)+
LD (STACK_POINTER)+
LD (STACK_POINTER)+

LD $STACK_POINTER
ST $STACK_FIX_POINTER

LD $STOPPER
ST (STACK_POINTER)+
ST (STACK_POINTER)+

MOVE_ELEMENTS:
	LD (STACK_POINTER)
	CMP $STOPPER
	BEQ STOP
	ST (STACK_FIX_POINTER)+
	LD $STOPPER
	ST (STACK_POINTER)+
	JUMP $MOVE_ELEMENTS
STOP:
	CLA
	ST $STACK_FIX_POINTER
	LD $STACK_START
	ST $STACK_POINTER
	HLT
